---
title: "Birmingham Pharmacy Access"
author: "David Ellis"
format: 
  html:
    embed-resources: true
editor: source
echo: false
warning: false
theme:
  light: flatly
  dark: darkly
---

```{r setup}
library(readxl)
library(dplyr)
library(janitor)
library(leaflet)
library(htmltools)
library(sf)
library(BSol.mapR)
library(wmSpatial)
source("functions.R")

# 1 mile in km
key_distance_km = 1.609344
```


## Current Pharmacy Provision

```{r load-pharm-data}

pharm_data <- read.csv("../data/birmingham_geocoded.csv") %>%
  clean_names() %>%
  rename(
    postcode = birmingham_post_code,
    name = birmingham_organisation_name) %>%
  select(
    postcode, name, contains("opening_hours"), birmingham_contract_type
  ) %>%
  mutate(
    popup_text = paste0(
      "<b>", name, "</b><br><br>",
      "<b>Monday</b>:", birmingham_pharmacy_opening_hours_monday, "<br>",
      "<b>Tuesday</b>:", birmingham_pharmacy_opening_hours_tuesday, "<br>",
      "<b>Wednesday</b>:", birmingham_pharmacy_opening_hours_wednesday, "<br>",
      "<b>Thursday</b>:", birmingham_pharmacy_opening_hours_thursday, "<br>",
      "<b>Friday</b>:", birmingham_pharmacy_opening_hours_friday, "<br>",
      "<b>Saturday</b>:", birmingham_pharmacy_opening_hours_saturday, "<br>",
      "<b>Sunday</b>:", birmingham_pharmacy_opening_hours_sunday
    )
  )%>%
  filter(
    # Filter out distance prescribing pharmacies
    birmingham_contract_type != "DAC"
  )

pharm_data_pcs <- join_postcode_info(pharm_data)

```
:::{.panel-tabset}

## All Days

There are currently `r nrow(pharm_data)` pharmacies in Birmingham.

```{r map-pharm-locs-all-days}
#| fig-width: 6
#| fig-height: 5.5

day = ""

pharm_access_1km_sf <- get_lsoa_access_sf(
  pharm_data, 
  radius_km = key_distance_km, 
  day_filter = day
)

plot_access_map(
    pharm_access_1km_sf,
    pharm_data_pcs,
    "Estimated Population<br>within 1 mile of a<br>Pharmacy (All Days)",
    day_filter = day
  )

```

## Saturday

There are currently `r nrow(pharm_data)` pharmacies in Birmingham.

```{r map-pharm-locs-sat}
#| fig-width: 6
#| fig-height: 5.5

day = "Saturday"

pharm_access_1km_sf <- get_lsoa_access_sf(
  pharm_data, 
  radius_km = key_distance_km, 
  day_filter = day
)

plot_access_map(
    pharm_access_1km_sf,
    pharm_data_pcs,
    "Estimated Population<br>within 1 mile of a<br>Pharmacy (Saturday)",
    day_filter = day
  )

```

## Sunday

There are currently `r nrow(pharm_data)` pharmacies in Birmingham.

```{r map-pharm-locs-sun}
#| fig-width: 6
#| fig-height: 5.5

day = "Sunday"

pharm_access_1km_sf <- get_lsoa_access_sf(
  pharm_data, 
  radius_km = key_distance_km, 
  day_filter = day
)

plot_access_map(
    pharm_access_1km_sf,
    pharm_data_pcs,
    "Estimated Population<br>within 1 mile of a<br>Pharmacy (Sunday)",
    day_filter = day
  )

```

:::